service:
  name: project-service

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'}
  environment:
    MONGO_DB_URI: ${env:MONGO_DB_URI, file(./config/${self:provider.stage}.js):db.uri}
    MONGO_DB_NAME: ${env:MONGO_DB_NAME, file(./config/${self:provider.stage}.js):db.name}-${self:provider.stage}
    MONGO_DB_PARAMS: ${env:MONGO_DB_PARAMS, file(./config/${self:provider.stage}.js):db.params}

functions:
  getProject:
    handler: handlers/get.get
    events:
      - http:
          method: get
          path: projects/{id}


  getManyProjects:
    handler: handlers/getMany.getMany
    events:
      - http:
          method: get
          path: projects

  createProject:
    handler: handlers/create.create
    events:
      - http:
          method: post
          path: projects

  setGroup:
    handler: handlers/setGroup.setGroup
    events:
      - http:
          method: put
          path: projects/{id}/group

custom:
  webpackIncludeModules: true
  serverless-offline:
    port: 3001